
createTask('broken') {
    throw new RuntimeException('failure')
}
